### ISSUE TITLE
Chrome supporting single hash #targetText=

### ISSUE THREAD

**Issue by remy** [WICG/ScrollToTextFragment#24]
Chrome has landed this spec behind a flag: https://www.chromestatus.com/features/4733392803332096 - but the implementation uses a single hash - I don't suppose you have any idea why? 

Or whether this is somehow a bug in their implementation?

**Comment by frank-e** [comment]
Out of curiosity I checked why a **#** is not permitted in an URI fragment as defined in STD 66 (RFC 3986, same idea as WhatWG URLs without UTF-8), and found the old [erratum 3330](https://www.rfc-editor.org/errata/eid3330), submitted and rejected in 2012: Allegedly applications parsing the fragment right to left existed.

**Comment by bokand** [comment]
Thanks, I hadn't seen that. I did get the same reason in my [question to the uri mailing list](https://lists.w3.org/Archives/Public/uri/2019Sep/0002.html)

**Comment by bokand** [comment]
Update: Chrome M79 will uses the most recent spec; only the `:~:` delimiter will be accepted and the directive is `text=`. E.g:

```
https://example.com#:~:text=foo
```

The old syntax forms (`##targetText=...`, `#targetText=...`) have been removed.

FYI: The fragment directive (i.e. `:~:text=foo`) must still appear inside a URL fragment (after a `#`). This ensures some level of backwards compatibility in UAs that don't yet implement the feature (the link won't scroll to the text but it'll still load the correct resource).
