### ISSUE TITLE
Needs to spec security mitigations

### ISSUE THREAD

**Issue by bokand** [WICG/ScrollToTextFragment#46]
The explainer's [Security](https://github.com/WICG/ScrollToTextFragment#security) section discusses several restrictions on the feature; however, they're not mentioned at all in the spec.

At the least, the spec should add some implementer notes around the security issues here but it might make sense to make these normative requirements, given that not implementing them could be harmful to users.

**Comment by yoavweiss** [comment]
A [comment](https://github.com/w3ctag/design-reviews/issues/392#issuecomment-510855073) from @annevk on the TAG review also seems like something we'd need to normatively address.
