### ISSUE TITLE
Clarify display locking use for scroll-to-text-fragment feature

### ISSUE THREAD

**Issue by dvoytenko** [WICG/ScrollToTextFragment#68]
Is this feature aimed to cross-operate with the display locking API?

**Comment by bokand** [comment]
Yes, I believe it should work exactly like Find-in-Page or element-id fragments, both of which are explicitly called out in the [display-locking explainer](https://github.com/WICG/display-locking).

I don't think there's anything for us to explicitly mention, i.e. in the spec. It seems like that would be up to the display-locking spec? @chrishtr, This feature should definitely work with display-locking, is there anything we need to do to opt-into it, either from implementation or from spec?

**Comment by chrishtr** [comment]
I don't think there is anything to call out on your end. The `rendersubtree` spec will call out scroll to text fragment as a triggering use case.

**Comment by bokand** [comment]
Thanks Chris, in that case will close this issue.
